# Generated by Django 4.1.4 on 2023-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0003_alter_resumemodel_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_project', models.ImageField(upload_to='')),
                ('name_project', models.CharField(max_length=20)),
                ('summary_project', models.CharField(max_length=300)),
            ],
        ),
    ]
