# Generated by Django 4.1.4 on 2023-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0004_resumeins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeins',
            name='picture_project',
            field=models.ImageField(upload_to='InsImages'),
        ),
    ]
