# Generated by Django 4.1.4 on 2023-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0005_alter_resumeins_picture_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeins',
            name='picture_project',
            field=models.ImageField(upload_to=''),
        ),
    ]
