# Generated by Django 4.1.4 on 2023-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0006_alter_resumeins_picture_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeins',
            name='link_project',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
